services:
    php:
        build:
            context: ./
        volumes:
            - .:/app:cached
        working_dir: /app
        container_name: kk_php

    nginx:
        image: nginx:1.15.8-alpine
        ports:
            - 127.0.0.1:${NGINX_PORT}:80
        volumes:
            - .:/app:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,cached
        container_name: kk_nginx
